<?php

namespace Proxies\__CG__\AppBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class AgCrop extends \AppBundle\Entity\AgCrop implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'AppBundle\\Entity\\AgCrop' . "\0" . 'price', '' . "\0" . 'AppBundle\\Entity\\AgCrop' . "\0" . 'amount', '' . "\0" . 'AppBundle\\Entity\\AgCrop' . "\0" . 'producedDate', '' . "\0" . 'AppBundle\\Entity\\AgCrop' . "\0" . 'expirationDate', '' . "\0" . 'AppBundle\\Entity\\AgCrop' . "\0" . 'onhold', '' . "\0" . 'AppBundle\\Entity\\AgCrop' . "\0" . 'id', '' . "\0" . 'AppBundle\\Entity\\AgCrop' . "\0" . 'product', '' . "\0" . 'AppBundle\\Entity\\AgCrop' . "\0" . 'producer');
        }

        return array('__isInitialized__', '' . "\0" . 'AppBundle\\Entity\\AgCrop' . "\0" . 'price', '' . "\0" . 'AppBundle\\Entity\\AgCrop' . "\0" . 'amount', '' . "\0" . 'AppBundle\\Entity\\AgCrop' . "\0" . 'producedDate', '' . "\0" . 'AppBundle\\Entity\\AgCrop' . "\0" . 'expirationDate', '' . "\0" . 'AppBundle\\Entity\\AgCrop' . "\0" . 'onhold', '' . "\0" . 'AppBundle\\Entity\\AgCrop' . "\0" . 'id', '' . "\0" . 'AppBundle\\Entity\\AgCrop' . "\0" . 'product', '' . "\0" . 'AppBundle\\Entity\\AgCrop' . "\0" . 'producer');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (AgCrop $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function setPrice($price)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPrice', array($price));

        return parent::setPrice($price);
    }

    /**
     * {@inheritDoc}
     */
    public function getPrice()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPrice', array());

        return parent::getPrice();
    }

    /**
     * {@inheritDoc}
     */
    public function setAmount($amount)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAmount', array($amount));

        return parent::setAmount($amount);
    }

    /**
     * {@inheritDoc}
     */
    public function getAmount()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAmount', array());

        return parent::getAmount();
    }

    /**
     * {@inheritDoc}
     */
    public function setProducedDate($producedDate)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setProducedDate', array($producedDate));

        return parent::setProducedDate($producedDate);
    }

    /**
     * {@inheritDoc}
     */
    public function getProducedDate()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProducedDate', array());

        return parent::getProducedDate();
    }

    /**
     * {@inheritDoc}
     */
    public function setExpirationDate($expirationDate)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setExpirationDate', array($expirationDate));

        return parent::setExpirationDate($expirationDate);
    }

    /**
     * {@inheritDoc}
     */
    public function getExpirationDate()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getExpirationDate', array());

        return parent::getExpirationDate();
    }

    /**
     * {@inheritDoc}
     */
    public function setOnhold($onhold)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setOnhold', array($onhold));

        return parent::setOnhold($onhold);
    }

    /**
     * {@inheritDoc}
     */
    public function getOnhold()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOnhold', array());

        return parent::getOnhold();
    }

    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setProduct(\AppBundle\Entity\AgProduct $product = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setProduct', array($product));

        return parent::setProduct($product);
    }

    /**
     * {@inheritDoc}
     */
    public function getProduct()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProduct', array());

        return parent::getProduct();
    }

    /**
     * {@inheritDoc}
     */
    public function setProducer(\AppBundle\Entity\AgUser $producer = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setProducer', array($producer));

        return parent::setProducer($producer);
    }

    /**
     * {@inheritDoc}
     */
    public function getProducer()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProducer', array());

        return parent::getProducer();
    }

}
